# Game system constants
GAME_NAME = "My Game [Change Name Later]"
SCREEN_INIT_SIZE = (1280, 960)
FRAME_CAP = 60
TEMP_MOVEMENT_FACTOR = 200
DISPLAY_SIZE = (640, 360)
# DISPLAY_SIZE = (960, 540)
#DISPLAY_SIZE = (3440, 1440)

# Map constants
TILE_SIZE = 32
WORLD_HEIGHT = TILE_SIZE * 5
CHUNK_SIZE = 64
PADDING = 3

# Physics system constants
SPATIAL_GRID_PARITION_SIZE = TILE_SIZE * 8
MAX_COLLISION_PASSES = 5